name: Build Image from Dockerfile 
on:
  workflow_dispatch:
  schedule:
    # Run once a week on Fridays
    - cron: "0 0 * * FRI"

jobs:
  build_image:
    name: Build ${{ matrix.prefix }} image for ${{ matrix.arch }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
         - prefix: manylinux
           version: '2_38'
           arch: loongarch64
           platforms: linux/loong64
           runs-on: ubuntu-latest
         - prefix: musllinux
           version: '1_2'
           arch: loongarch64
           platforms: linux/loong64
           runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: h5py/hdf5-manylinux
        ref: master

    - name: Patch Build
      run: |
        cp Dockerfile_manylinux_2_28_aarch64 Dockerfile_manylinux_2_38_loongarch64
        cp Dockerfile_musllinux_1_2_aarch64 Dockerfile_musllinux_1_2_loongarch64
        sed -i 's@FROM quay.io/pypa/manylinux_2_28_aarch64@FROM ghcr.io/loong64/manylinux_2_38_loongarch64@g' Dockerfile_manylinux_2_38_loongarch64
        sed -i 's@FROM quay.io/pypa/musllinux_1_2_aarch64@FROM ghcr.io/loong64/musllinux_1_2_loongarch64@g' Dockerfile_musllinux_1_2_loongarch64
        wget -qO - https://github.com/loong64/hdf5-manylinux/raw/refs/heads/master/install_hdf5_loong64.patch | git apply -v
        wget -qO - https://github.com/loong64/hdf5-manylinux/raw/refs/heads/master/install_libaec_loong64.patch | git apply -v
        git diff

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile_${{ matrix.prefix }}_${{ matrix.version }}_${{ matrix.arch }}
        platforms: ${{ matrix.platforms }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.prefix }}_${{ matrix.version }}_${{ matrix.arch }}-hdf5
        cache-from: ghcr.io/${{ github.repository_owner }}/${{ matrix.prefix }}_${{ matrix.version }}_${{ matrix.arch }}-hdf5
        