name: Build Image from Dockerfile 
on:
  workflow_dispatch:
  schedule:
    # Run once a week on Fridays
    - cron: "0 0 * * FRI"

jobs:
  build_loongarch64_wheels:
    name: Build image for loongarch64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: h5py/hdf5-manylinux
        ref: master

    - name: Patch Build
      run: |
        cp Dockerfile_aarch64 Dockerfile_loongarch64
        sed -i 's@quay.io/pypa/manylinux_2_28_aarch64@ghcr.io/loong64/manylinux_2_38_loongarch64@g' Dockerfile_loongarch64
        wget -qO - https://github.com/loong64/hdf5-manylinux/raw/refs/heads/master/install_hdf5_loong64.patch | git apply -v
        wget -qO - https://github.com/loong64/hdf5-manylinux/raw/refs/heads/master/install_libaec_loong64.patch | git apply -v
        git diff

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile_loongarch64
        platforms: linux/loong64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/${{ github.repository_owner }}/manylinux_2_38_loongarch64-hdf5
        cache-from: ghcr.io/${{ github.repository_owner }}/manylinux_2_38_loongarch64-hdf5
        